### ISSUE TITLE
Feedback statuses in 3.0 RC1

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-pjlink#61] opened 2023-06-01 19:48 UTC
Didn't notice when this was introduced but in the RC for 3.0 the feedbacks for power status works as imported from 2.4.2 BUT the selections are not available on new buttons or to edit current feedbacks.  Screenshot attached.  This is true for all 3 model Epsons I have.  L1500U, L510U, and L715 Powerlite.  Some feedbacks show as blank in the selection box others have numbers and "??".  When I click the feedback selection box it is blank.  You can tell there are line items delineated but no actual selection text. 

![projector feedback](https://github.com/bitfocus/companion-module-generic-pjlink/assets/51127807/29df2a54-a567-417c-b998-e7889b56cc2b)

**Comment by obcocav** [comment] 2023-06-02 01:46
The oldest build I had a copy of was 5827 and the issue is present there also.  Seems to be since the 3.0 update.  @istnv.  Maybe a similar issue to the one from the Denon Recorder Module?   Couldn't figure out how to take a screenshot without the selection box closing so here's a picture of the screen...:)
![IMG_0329](https://github.com/bitfocus/companion-module-generic-pjlink/assets/51127807/a31284bf-a152-4aef-a13e-ced75bec87af)

**Comment by DRJKNICKEL** [comment] 2023-06-04 13:41
Same here, with all sorts of Panasonic Beamers.
Use this feedback since possible. Since Version 3 its not working anymore.
Cant even select numbers. Status Window is empty, but i can select 4 different empty positions.
If i choose one of them, the whole Status Window appears in Blue Color

![Unbenannt](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/d0a9f652-8741-44b1-8ef0-a8bc8459ba5a)

**Comment by obcocav** [comment] 2023-06-04 15:08
@DRJKNICKEL.  Fixed in the latest betas.  Thanks @istnv!
Sent from my iPhone
On Jun 4, 2023, at 08:41, DRJKNICKEL ***@***.***> wrote:﻿
Same here, with all sorts of Panasonic Beamers.
Use this feedback since possible. Since Version 3 its not working anymore.
Cant even select numbers. Status Window is empty, but i can select 4 different empty positions.
If i choose one of them, the whole Status Window appears in Blue Color

**Comment by DRJKNICKEL** [comment] 2023-06-04 15:48
Good to know, thank you very much.Gesendet von Outlook für Android

**Comment by DRJKNICKEL** [comment] 2023-06-04 17:17
I just tried out, and as you said, the mentioned Problem ist solved.But the function of the Power State feedback itself doesnt show any colors on the button. Mute state works fine.I also couldnt change RGB or Hex values which are not in the color palette. For example i would like to change green into R 0 G 128 B 0 .In version 2.4.2 i can easily type in what i want.I also would like to use the AV Stumpfl Pixera Module. Is there any support soon?Kind regardsJan HeuserGesendet von Outlook für AndroidVon: obcocav ***@***.***>Gesendet: Sonntag, Juni 4, 2023 5:08:39 PMAn: bitfocus/companion-module-generic-pjlink ***@***.***>Cc: DRJKNICKEL ***@***.***>; Mention ***@***.***>Betreff: Re: [bitfocus/companion-module-generic-pjlink] Feedback statuses in 3.0 RC1 (Issue #61)
@DRJKNICKEL.  Fixed in the latest betas.  Thanks @istnv!Sent from my iPhoneOn Jun 4, 2023, at 08:41, DRJKNICKEL ***@***.***> wrote:﻿
Same here, with all sorts of Panasonic Beamers.
Use this feedback since possible. Since Version 3 its not working anymore.
Cant even select numbers. Status Window is empty, but i can select 4 different empty positions.
If i choose one of them, the whole Status Window appears in Blue Color

**Comment by DRJKNICKEL** [comment] 2023-06-04 17:19
I just tried out, and as you said, the mentioned Problem ist solved.But the function of the Power State feedback itself doesnt show any colors on the button. Mute state works fine.I also couldnt change RGB or Hex values which are not in the color palette. For example i would like to change green into R 0 G 128 B 0 .In version 2.4.2 i can easily type in what i wantGesendet von Outlook für AndroidVon: obcocav ***@***.***>Gesendet: Sonntag, Juni 4, 2023 5:08:39 PMAn: bitfocus/companion-module-generic-pjlink ***@***.***>Cc: DRJKNICKEL ***@***.***>; Mention ***@***.***>Betreff: Re: [bitfocus/companion-module-generic-pjlink] Feedback statuses in 3.0 RC1 (Issue #61)
@DRJKNICKEL.  Fixed in the latest betas.  Thanks @istnv!Sent from my iPhoneOn Jun 4, 2023, at 08:41, DRJKNICKEL ***@***.***> wrote:﻿
Same here, with all sorts of Panasonic Beamers.
Use this feedback since possible. Since Version 3 its not working anymore.
Cant even select numbers. Status Window is empty, but i can select 4 different empty positions.
If i choose one of them, the whole Status Window appears in Blue Color

**Comment by istnv** [comment] 2023-06-04 18:47
@DRJKNICKEL 
I test the module with the JBMIA emulation programs. Here is a snapshot of  my Companion test page ( the projector is in 'lamp cooling' mode, current input is not usually valid unless the projector is ON)
![image](https://github.com/bitfocus/companion-module-generic-pjlink/assets/51003420/46e8f386-9398-4fac-be8e-ce3703fc9ba8)

There are some projectors that interpret the specification differently and the replies needed for feedback does not match.
You may be able to collect the projector response on the debug screen. Click the `>_` on the connection page. 

Changing the color via the popup is a Companion core issue, and is usually a browser incompatibility.

**Comment by obcocav** [comment] 2023-06-04 18:57
@DRJKNICKL.  If you’re just coming over to v3 make sure you actually select a property like background color on the feedback for it to work.  I think it defaults with “properties” blank for the power feedback.  Add  the power state feedback then select background color property and select your colorSent from my iPhoneOn Jun 4, 2023, at 13:48, John Knight Jr ***@***.***> wrote:﻿
@DRJKNICKEL
I test the module with the JBMIA emulation programs. Here is a snapshot of  my Companion test page ( the projector is in 'lamp cooling' mode, current input is not usually valid unless the projector is ON)

There are some projectors that interpret the specification differently and the replies needed for feedback does not match.
You may be able to collect the projector response on the debug screen. Click the >_ on the connection page.
Changing the color via the popup is a Companion core issue, and is usually a browser incompatibility.

**Comment by DRJKNICKEL** [comment] 2023-06-04 20:41
Thanks for answering,  but as i said before im using this function in version 2.4.2 for all of our panasonic beamers, like DZ 21 or Rz 31/ RZ120.I know how to programm the feedbacks , the feedbacks for mute state works fine.Also if i put in the preset or variable text in the button name it tells me the right information in textform if the state is on or off.I also use a streamdeck and the feedback is always shown on the deck, in the browser or in the emulator or web buttons paralell.The only issue i got is, that if i programm a feedback for power state on the button wich usually also triggers the action via pj link or pixera control in togglemode or in several steps, the feedback color doesnt change from black to any other color i adjust in the feedback of that button. The connection is online and the action is triggered but no change of background color on power state feedback.Its not a problem using version 2.4.2. There are to many modules not supported anyway in version 3.But i thought it might be helpfull to share this information helping to improve the new pj link modul in version 3 or following beta version.Also that the value of rgb colors are not adjustable by custom an you have to choose fixed color presets.For normal background color of a button it still works fine, but not for background color of feedbacks.Kind regardsJanGesendet von Outlook für AndroidVon: obcocav ***@***.***>Gesendet: Sonntag, Juni 4, 2023 8:58:01 PMAn: bitfocus/companion-module-generic-pjlink ***@***.***>Cc: DRJKNICKEL ***@***.***>; Mention ***@***.***>Betreff: Re: [bitfocus/companion-module-generic-pjlink] Feedback statuses in 3.0 RC1 (Issue #61)
@DRJKNICKL.  If you’re just coming over to v3 make sure you actually select a property like background color on the feedback for it to work.  I think it defaults with “properties” blank for the power feedback.  Add  the power state feedback then select background color property and select your colorSent from my iPhoneOn Jun 4, 2023, at 13:48, John Knight Jr ***@***.***> wrote:﻿
@DRJKNICKEL
I test the module with the JBMIA emulation programs. Here is a snapshot of  my Companion test page ( the projector is in 'lamp cooling' mode, current input is not usually valid unless the projector is ON)

There are some projectors that interpret the specification differently and the replies needed for feedback does not match.
You may be able to collect the projector response on the debug screen. Click the >_ on the connection page.
Changing the color via the popup is a Companion core issue, and is usually a browser incompatibility.

**Comment by istnv** [comment] 2023-06-04 21:02
There has been a considerable re-write for 3.0 so if you are not seeing feedback, I need to know what your projector is sending since the module works fine with the emulator and the other projectors I have access to.

The RGB editor is a core issue and would not work for any module at the moment. You can enter a custom value in the Hex entry.

**Comment by obcocav** [comment] 2023-06-04 21:20
Nevermind.  My feedback is working but now the actual command for OFF is NOT working

EDIT.. The connections are timing out and going to UNKOWN STOPPED state until a cycle of the modules.  L1500U L510U L715

Once I cycle the modules all works well

**Comment by istnv** [comment] 2023-06-04 22:04
> Nevermind. My feedback is working but now the actual command for OFF is NOT working
> 
> EDIT.. The connections are timing out and going to UNKOWN STOPPED state until a cycle of the modules. L1500U L510U L715
> 
> Once I cycle the modules all works well

Anything in the log? That indicates a module crash.

**Comment by istnv** [comment] 2023-06-06 11:48
Module updates should be in the v3.0 build sometime today.

**Comment by DRJKNICKEL** [comment] 2023-06-06 12:41
Thank you very much :)Gesendet von Outlook für Android

**Comment by mabyoro** [comment] 2023-06-22 09:04
recently installed 3.0.0.-rc2 and unfortunately Power On Feedback doesn't work. 
![image](https://github.com/bitfocus/companion-module-generic-pjlink/assets/97915519/cdf1ba64-54af-417c-8b0e-d147b595a294)
![image](https://github.com/bitfocus/companion-module-generic-pjlink/assets/97915519/2cad10c2-9f7b-49ec-a926-46c8f5687a02)
as you can see all 3 different Panasonic-Projectors are giving correct feedback to the right 3 Buttons. But the module doesn't change background-color, as you can see in the 3 left buttons.

**Comment by istnv** [comment] 2023-06-22 18:09
@mabyoro Can you post how your buttons are set up?
All of my testing works as documented with the projectors I have access to.

**Comment by DRJKNICKEL** [comment] 2023-06-23 14:17
![Buttons On 2](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/96f84ac8-38a4-408d-9472-174973ea0181)
![Buttons UET](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/2f278b59-dbbe-4e62-b54a-7ee8a2663fb2)

**Comment by DRJKNICKEL** [comment] 2023-06-23 14:23
mabyoro is a colleague of me :)
variable function works fine in the second row.
But selected feedback based on power state does still not work properly.
On and Cooling doesnt show any color

**Comment by DRJKNICKEL** [comment] 2023-06-23 14:25
![Buttons off_cooling](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/8efe1cd7-7023-4e1c-a7b6-02e3389d0a88)

**Comment by DRJKNICKEL** [comment] 2023-06-23 16:54
![log](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/0ced865e-f77f-4f12-a630-ad16611c0c8c)

**Comment by DRJKNICKEL** [comment] 2023-06-23 16:56
![Screenshot 2023-06-23 185554](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/24aff56d-604d-402e-bc6b-ed4d94d7e18b)

**Comment by istnv** [comment] 2023-06-23 19:03
@DRJKNICKEL I still need the module log:
![image](https://github.com/bitfocus/companion-module-generic-pjlink/assets/51003420/daea4d65-2071-4078-bd59-30069c959402)
This will open a debug window with more information.

**Comment by DRJKNICKEL** [comment] 2023-06-23 19:11
![debug](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/6e6f3a36-7680-4e0d-bf7d-35e73092353b)

**Comment by DRJKNICKEL** [comment] 2023-06-23 19:12
in none of the connections is listed anything i am afraid

**Comment by DRJKNICKEL** [comment] 2023-06-23 19:15
![debug 2](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/4075e210-f86b-4a69-9921-a4e00f204783)

**Comment by DRJKNICKEL** [comment] 2023-06-23 19:15
this was after pressing every function in the debug window

**Comment by istnv** [comment] 2023-06-23 19:16
Run through a power on, power off cycle and post the results.

**Comment by istnv** [comment] 2023-06-23 19:19
What is strange is the variable is correct, but the feedback does not match. Was this a configuration updated from 2.4?

**Comment by mabyoro** [comment] 2023-06-23 19:22
No! It is newly made via 3.0.0-rc2

**Comment by DRJKNICKEL** [comment] 2023-06-23 19:25
i will try the power on/off circle afterwards.
Cant shut down the Projector at the Moment, cause it is part of the show at the moment

**Comment by DRJKNICKEL** [comment] 2023-06-23 20:33
did the cycle, but still no informations. 
except in the log

**Comment by DRJKNICKEL** [comment] 2023-06-23 20:33
![wrapper](https://github.com/bitfocus/companion-module-generic-pjlink/assets/135520928/cdaefad8-c3f8-430b-9526-2e59df19b845)

**Comment by istnv** [comment] 2023-06-23 20:38
That looks like a networking issue. 
Is another computer or something else connected via ethernet to that projector's PJLink port?
Click on the dimmed buttons at the top of that log for more information.

**Comment by mabyoro** [comment] 2023-06-23 20:43
Yes, normally there are two PCs connected to all projectors via PJLink. But this is a state since the last years and including to 2.4.2 it worked perfectly.

**Comment by istnv** [comment] 2023-06-23 21:08
this is hard to fix since I cannot reproduce the problem. 
Did you get a chance to look at the rest of the log? 
The dimmed buttons (warning/info/debug) at the top are filtering anything not an error.

**Comment by istnv** [comment] 2023-06-23 22:46
I was able to reproduce this effect by setting up 2 dummy PJs.
From what I can discover so far, the issue is Companion, not the module.
I am opening another issue and closing this one for now.

**Comment by istnv** [comment] 2023-06-23 23:38
This will be in the next beta build.

**Closed as completed** 2023-06-23 23:38 UTC

**Comment by mabyoro** [comment] 2023-07-02 22:00
![IMG_0169](https://github.com/bitfocus/companion-module-generic-pjlink/assets/97915519/a1e8816e-bee0-4e57-930f-05100d882b4e)
Looks solved for me in 3.0.0+6007
